Feature/107 글/댓글 등록 시 결과를 스낵바로 고지한다.
woowacourse-teams/2020-doran-doran pull request #109
Opened 2020-08-18 15:52 UTC by hwookim

Resolves #107 
리뷰는 목요일 오전까지 부탁드려요~

이젠 엔터키로도 댓글 등록이 가능하답니다!
댓글은 실패 시 스낵바도 적용이 안되어있길래 한번에 다 처리했어요.
기존 로직도 제가 약간 바꾼 부분이 있으니 확인 부탁드려요~~~~

2020-08-19 06:20 UTC, LTTTTTE approved these changes
잘 작동하네요~ 고생했어요~

2020-08-19 06:39 UTC, YebinK requested changes
수고했어요 👍 
코멘트 하나 달았으니 확인해주세요~ 🙂

2020-08-19 06:39 UTC, YebinK commented on front/src/components/post/PostDetailPage.vue
> +    <v-snackbar v-model="snackbarWarning" timeout="1500" top>
지금 상태라면 페이지가 늘어날수록 해당 페이지에서 필요한 snackbar가 추가될 것 같은데요,
snackbar를 전역으로 관리할 수 있을 것 같네요!

수정해볼까요? 🙂

2020-08-19 16:29 UTC, hwookim commented on front/src/components/post/PostDetailPage.vue
> +    <v-snackbar v-model="snackbarWarning" timeout="1500" top>
해봤는데 생각대로 뙇 작동하질 않네요....ㅠㅠ
내일까지만 좀 해보고 안되면 포기해야 할지도 모르겠어요...😢

2020-08-20 09:00 UTC, hwookim commented on front/src/components/post/PostDetailPage.vue
> +    <v-snackbar v-model="snackbarWarning" timeout="1500" top>
와 성공했어요! computed setter가 참 미묘하네요...

2020-08-20 09:20 UTC, YebinK approved these changes

2020-08-20 09:21 UTC, YejiAhn approved these changes
프론트 전반적 리팩터링부터 수고 정말 많았어요 우 최고 👍

2020-08-20 10:46 UTC, merged