feature/104 LoginPage 화면과 MyPage 사이드바를 만든다.
woowacourse-teams/2020-doran-doran pull request #115
Opened 2020-08-20 08:16 UTC by YebinK

Resolves #104 

- 로그인 화면 (로그인 없이 둘러보기, 카카오톡으로 로그인하기) 구현
- AppBar에서 마이페이지로 이동하는 사이드바 구현

리뷰는 8/21 (금) 18:00 까지 해주세요!

2020-08-20 15:57 UTC, hwookim requested changes
사이드바가 정말 예쁘네요! 👍 👍 
고생 많았어요 엘리!

좀 리뷰를 많이 달았네요...😅
리뷰를 하다보니 약간 스스로 고민이 되는 점이 있어요.
간결한 코드가 확실히 후에 수정하기는 편하겠지만, 지금 이렇게까지 신경써야하나 싶은 느낌이 드네요....
저도 스스로가 많은 경험이 있거나 '이게 맞다!'라고 말할 만한 사람이 아니라 더 그런 것 같아요.😢

이번에는 v-list 쪽이 참 애매한 거 같아요.
코드 상에서는 더 간결하게 표현할 수 있을텐데, 다른 예제들을 보면 계층 구조가 많이 들어가있더라고요.
어떤게 좀 더 올바른 쪽일까요? 정답은 없을지도 모르겠지만요...ㅠㅠ😥

2020-08-23 19:02 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +      <v-icon v-show="myPageButton" @click.stop="goToMyPage">
상위 컴포넌트에 이벤트가 걸려있지 않으므로 필요 없겠네요 😄 
다시 한 번 공부합니다! ㅎㅎ

2020-08-23 19:05 UTC, YebinK commented on front/src/components/login/LoginPage.vue
> +img {
id로 분리했습니다 👍

2020-08-23 19:05 UTC, YebinK commented on front/src/components/login/LoginPage.vue
> +}
좋은 생각이네요! 앞으로는 전체적으로 적용해야 할만한 스타일인지 함께 고민해보겠습니다 :)

2020-08-23 19:13 UTC, YebinK commented on front/src/components/login/LoginPage.vue
> +}
left: 50%;
transform: translate(-50%);

요놈들을 함께 써서 가운데 배치를 할 수 있군요! 배워갑니다 👍

2020-08-23 19:29 UTC, YebinK commented on front/src/components/member/MyPageSideBar.vue
> +    <v-list>
클릭한 아이템을 누르면 해당 페이지로 이동할 것이기 때문에 일부러 남겨둔 것입니다!
추후 페이지가 생기면 어떤 방식이 더 적합할지 다시 논의해봐요 🙂

2020-08-23 19:31 UTC, YebinK commented on front/src/components/member/MyPageSideBar.vue
> +        <v-list-item v-for="item in items" :key="item.title" link>
group 값은 클릭한 아이템을 저장하기 위해 둔 것인데요, 바로 위의 내용과 같은 맥락인 것 같네요!

2020-08-23 19:38 UTC, YebinK commented on front/src/components/member/MyPageSideBar.vue
> +  name: "MyPageSideBar",
아주 마음에 듭니다
메소드명까지 xxSideBar -> xxSidebar로 변경할게요.

2020-08-23 20:25 UTC, YebinK commented on front/src/store/modules/appBar.js
> +    },
지난번에 의논했던 단어의 중복 문제를 적용해
SHOW_APP_BAR -> SHOW
HIDE_APP_BAR -> HIDE
appbar -> visible
sidebar -> visible
로 변경했습니다.

2020-08-23 20:27 UTC, YebinK commented on front/src/components/login/LoginPage.vue
> +    rgba(234, 77, 44, 1) 0%,
App.vue에 doran-doran-color 클래스를 두었습니다. 이제 이걸 사용하시면 될 것 같아요 🙂

2020-08-24 04:58 UTC, hwookim requested changes
화이팅!

2020-08-24 04:58 UTC, hwookim commented on front/src/App.vue
> +      showMyPageModal: false,
sidebar로 바꿔주세요~

2020-08-24 04:58 UTC, hwookim commented on front/src/store/modules/appBar.js
> +    TOGGLE(state) {
HIDE가 있으니 TOGGLE보단 SHOW로 해서 확실히 하는 건 어때요?

2020-08-24 06:33 UTC, LTTTTTE approved these changes

2020-08-24 07:32 UTC, hwookim approved these changes

2020-08-24 07:38 UTC, YejiAhn approved these changes
💯

2020-08-24 07:51 UTC, merged