Feature/82 카카오 로그인 기능을 구현한다.
woowacourse-teams/2020-doran-doran pull request #116
Opened 2020-08-20 11:17 UTC by LTTTTTE

Resolves #82 

로컬환경에서 실행시 application.properties에 값을 추가해야합니다.

2020-08-21 07:56 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/exception/InvalidAuthenticationException.java
> +    public InvalidAuthenticationException(String message) {
상수화 완료~

2020-08-21 07:56 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/config/jwt/JwtTokenProvider.java
> +            return true;
좋은 정보 감사합니다.

2020-08-21 07:56 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/exception/CommentOwnerMisMatchException.java
> +public class CommentOwnerMisMatchException extends ExpectedException {
Author 좋군요 반영하겠습니다.

2020-08-21 07:57 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/exception/CommentLikerMisMatchException.java
> +public class CommentLikerMisMatchException extends ExpectedException {
네

2020-08-21 07:57 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/comment/domain/CommentLike.java
> +    }
메소드를 사용하도록 수정 했습니다.

2020-08-23 19:52 UTC, YejiAhn requested changes
그저.. 갓 오구.. 👏👏👏
정말 방대한 양의 PR이네요. 
정말 수고 많으셨어요! 간단한 코멘트 몇 개 달아뒀습니다!

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/comment/controller/CommentController.java
> +        @LoginMember Member member) {
저도 동의해요 오구! 🙃

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/comment/domain/Comment.java
> +        return this.author.getId().equals(member.getId());
디미터 법칙을 지킨다면 Member 객체를 조금 더 객체처럼 써 볼 수도 있겠네요 🙂

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/common/exception/CommentAuthorMisMatchException.java
> +public class CommentAuthorMisMatchException extends ExpectedException {
Mismatch는 한 단어니까 CommentAuthorMismatchException 이라고 써 줄 수 있을 것 같아요 🙂  다른 MismatchException 들도 적용 부탁드립니다! 😄

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentLikeService.java
> +            throw new CommentLikerMisMatchException();
@YebinK 메세지를 통일하고자 하는 것이 목적이라면 ExpectedException을 상속받는 MismatchException을 네 개 각각의 Exception이 상속하게 한 다음 MismatchException에서 지정해준 message까지를 상속받게 할 수 있지 않을까요? 하지만 너무 광범위한 메세지가 사용자에게 좋을지는 잘 모르겠어요.

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/common/CommonAdvice.java
> +    public ResponseEntity<ErrorResponse> handleEntityValidationException(
메서드명이 `handleEntityValidationException`이 맞나요?
`handleAuthenticationValidationException`은 어떨까요?

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/common/exception/InvalidAuthenticationException.java
> +@ResponseStatus(HttpStatus.UNAUTHORIZED)
위에 CommonAdvice에서도 status code를 명시해준 것을 봤는데 둘 다 써주는 것이 맞나요?
(이렇게 관리하는 Exception이 현재 프로젝트에 아무것도 존재하지 않네요. 통일성을 해칠 수도 있을 것 같아요 🙂 )

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/common/exception/PostAuthorMisMatchException.java
> +
공백 라인이 들어갔네요 😦

2020-08-23 19:52 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/post/domain/Post.java
> +        return this.author.getId().equals(member.getId());
Member가 같은 member인지 확인해줄 수 있는 로직을 가지고 있다면 이 부분도 해결되겠네요!

2020-08-24 05:45 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/CommonAdvice.java
> +        InvalidAuthenticationException e) {
적용하겠습니다.

2020-08-24 05:48 UTC, LTTTTTE commented on build.gradle
> +    implementation 'org.springframework.security:spring-security-oauth2-jose'
그렇군요. 배워갑니다.

2020-08-24 05:51 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentService.java
> +
동의합니다

2020-08-24 05:59 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/config/security/OAuth2ClientService.java
> +        if (!memberRepository.existsMemberByoAuthId(id)) {
setter 뚫어서 적용하겠습니다.

2020-08-24 06:01 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/exception/InvalidAuthenticationException.java
> +@ResponseStatus(HttpStatus.UNAUTHORIZED)
불필요함으로 제거하겠습니다.

2020-08-24 06:02 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/post/domain/Post.java
> +    @ManyToOne
그렇군요!

2020-08-24 06:03 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentService.java
> +
맞아요

2020-08-24 06:03 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/CommonAdvice.java
> +        InvalidAuthenticationException e) {
네

2020-08-24 06:04 UTC, chws approved these changes
정말 많은 부분에 변경이 있었네요 오구! 👏👏 수고하셨습니다.
다른 분들이 리뷰를 잘 남겨주셔서 저는 이만 approve 할게요!

2020-08-24 06:28 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/config/security/OAuth2ClientService.java
> +import sun.reflect.generics.reflectiveObjects.NotImplementedException;
맞습니다.

2020-08-24 06:30 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/exception/CommentAuthorMisMatchException.java
> +public class CommentAuthorMisMatchException extends ExpectedException {
적용하겠습니다.

2020-08-24 06:31 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/common/CommonAdvice.java
> +    public ResponseEntity<ErrorResponse> handleEntityValidationException(
복사붙여넣기를해서 생긴 문제입니다. 수정하겠습니다.

2020-08-24 06:35 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/config/jwt/JwtConfig.java
> +            .addPathPatterns("/**");
현재 코드에선 / , /map이 존재하지 않기때문에 rebase이후 실제 로컬테스트를 이후 수정해보겠습니다.

2020-08-24 06:39 UTC, LTTTTTE commented on front/src/api/member.js
> +          nickname: "미인증 사용자",
좋은 의견입니다.

2020-08-24 06:42 UTC, LTTTTTE commented on src/main/java/com/grasshouse/dorandoran/comment/domain/Comment.java
> +        return this.author.getId().equals(member.getId());
동의합니다. 수정하겠습니다.

2020-08-24 08:56 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentLikeService.java
> +            throw new CommentLikerMisMatchException();
이런 식으로 생각했었는데.. 어떤가요?

```java
public class MemberMismatchException extends ExpectedException {

    public static final String MEMBER_POST_MISMATCH_MESSAGE = "회원님의 글이 아닙니다.";
    public static final String MEMBER_COMMENT_MISMATCH_MESSAGE = "회원님의 댓글이 아닙니다.";
    public static final String MEMBER_POST_LIKE_MISMATCH_MESSAGE = "회원님이 좋아요 한 글이 아닙니다.";
    public static final String MEMBER_COMMENT_LIKE_MISMATCH_MESSAGE = "회원님이 좋아요 한 댓글이 아닙니다.;

    public MemberMismatchException(String message) {
        super(message);
    }
}
```

2020-08-25 05:22 UTC, YebinK approved these changes

2020-08-25 06:02 UTC, YejiAhn approved these changes
빛오구 갓오구 💯

2020-08-25 06:18 UTC, merged