feature/105 글 상세화면에서 글 위치가 있는 지도를 모달로 띄워준다.
woowacourse-teams/2020-doran-doran pull request #118
Opened 2020-08-21 08:04 UTC by chws

Resolves #105

2020-08-24 05:18 UTC, YejiAhn requested changes
베젤 크기도 그렇고 디자인 너무 예뻐요! 레베카 고생 많았어요 💯 
간단한 코멘트 몇 개 남길게요!

2020-08-24 05:18 UTC, YejiAhn commented on front/src/components/post/PostDetailPage.vue
> +    async changeMode() {
저도 이 의견에 동의합니다 🙂

2020-08-24 05:18 UTC, YejiAhn commented on front/src/components/post/PostDetailPage.vue
> +          "postDetailModal/CHANGE_MODE",
(아마 바뀌겠지만..)
CHANGE_MODE 보다는 SET_MODE 등의 이름이 더 어울리는 것 같아요.

2020-08-24 05:18 UTC, YejiAhn commented on front/src/components/post/PostMapModal.vue
> +  name: "PostMapModal",
`MapModalOfPostLocation` 은 어떤가요? 
`PostLocationMapModal` 이나..

2020-08-24 05:18 UTC, YejiAhn commented on front/src/components/post/PostMapModal.vue
> +  async mounted() {
mounted 함수 깔끔하네요! 👍

2020-08-24 05:18 UTC, YejiAhn commented on front/src/store/modules/postDetailModal.js
> +import { POST_MODE } from "@/utils/constants";
저도 오히려 전역으로 관리되는 MODE 친구들 때문에 코드를 이해하는 데 어려웠던 것 같아요 😢 
vuex로 빼지 않고 구현할 수 있다면 더 가독성 좋은 코드가 나올 것 같아요!

2020-08-24 08:12 UTC, chws commented on front/src/components/post/PostMapModal.vue
> +  name: "PostMapModal",
PostDetailPageLocationMapModal 로 바꿔봤는데 이름이 상당히 길어졌어요..ㅋㅋㅋ

2020-08-24 08:18 UTC, chws commented on front/src/components/post/PostDetailPage.vue
> +        {{ post.address.depth3 }}에 외침
오 좋은 방법인 것 같아요!

2020-08-25 06:57 UTC, YebinK approved these changes

2020-08-25 07:23 UTC, hwookim approved these changes

2020-08-25 07:28 UTC, YejiAhn reviewed
레베카 눈에 보이는게 있네요!
그리고 mode 관련 리뷰도 반영해주세요 레베카 🥰

2020-08-25 07:28 UTC, YejiAhn commented on front/src/components/post/PostDetailPage.vue
> +          {{ post.address.depth3 }}</span
오 여기..!

2020-08-25 07:50 UTC, YejiAhn approved these changes
수고했습니다! 😄

2020-08-25 07:52 UTC, merged