feature/114 검색 기능을 지도의 AppBar에서만 가능하도록 한다.
woowacourse-teams/2020-doran-doran pull request #120
Opened 2020-08-22 17:52 UTC by YebinK

Resolves #114 

생각보다 오래 걸렸네요! 😅
단순히 검색창의 위치만 바꾸면 될 줄 알았는데,
+검색 결과를 PostOverlay와 clusterer에 적용하려다보니
+v-for의 re-rendering 관련 이슈가 생겨서 해결하느라 조금 늦었습니다.

도움을 준 @hwookim 고마워요! 😀
트랜지션을 넣어준 @LTTTTTE 도 고맙습니다 😀
기다려준 @chws 와 @YejiAhn 도 고마워요! 😀

리뷰는 월요일 오전까지 해주세요!

2020-08-24 06:01 UTC, YejiAhn requested changes
엘리 수고 많았어요! 빨리 엘리의 검색 기능과 저의 시간 필터기능을 머지하고 싶군요 후후,,
간단한 리뷰 달았습니다!

2020-08-24 06:01 UTC, YejiAhn commented on front/src/components/DoranAppBar.vue
> +        data.endDate = "2020-09-20" + " 23:59:59";
이 상수들은 뭔가요? 🤔

2020-08-24 07:40 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +        />
예지 의견에 동의합니다!
모바일 환경을 타겟으로 하기 때문에 없어도 된다고 생각해요!

2020-08-24 07:41 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +}
아이코 이친구도 app.vue에 빼둬야겠네요 ㅎㅎ

2020-08-24 09:04 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +      await this.$store.dispatch("post/searchPosts", data);
예지가 저 부분 작업을 하고 있어서 그냥 놔둔 것이었습니다 🙂 
머지되고 예지 브랜치에서 추가 작업할게요~

2020-08-24 11:14 UTC, LTTTTTE reviewed
검색 input창 켜졌을때 autofocus 있는게 더 자연스럽다 생각해요

2020-08-24 18:02 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +    </v-expand-x-transition>
도와주셔서 더 멋진 앱바가 탄생했네요 👍 
바뀐 트랜지션도 상당히 마음에 드네요!

2020-08-24 18:04 UTC, YebinK commented on front/src/store/modules/post.js
> +      commit("SET_POSTS", searchResult);
저렇게 변경하면 insertBefore 문제가 그대로 발생해서 CLEAR_POSTS 메소드를 작성해두었습니다!

2020-08-25 02:42 UTC, YebinK commented on front/src/components/map/KakaoMap.vue
> +    },
1. computed.posts()는 작동하지 않습니다!
 아까 우가 말한대로 순환참조가 발생할 여지가 있어 error가 뜹니다.

2. watch 방식 아주 마음에 드네요 🙂 
clustered()는 posts 를 필터링하는 느낌이 들어서 watch가 훨씬 적절한 것 같아요. 변경하겠습니다~

2020-08-25 02:43 UTC, YebinK commented on front/src/components/map/PostCreateModal.vue
> +          elevation="2"
그림자 효과를 주는데 기본 그림자가 지정되어 있었네요!

2020-08-25 05:06 UTC, YebinK commented on front/src/components/DoranAppBar.vue
> +        data.endDate = "2020-09-20" + " 23:59:59";
예지가 작업하고 있는 부분이라 요청이 제대로 동작하는지 여부를 확인하고 싶어서 우선 상수로 뒀습니다! 나중에 합칩시다!ㅎㅎ

2020-08-25 07:56 UTC, hwookim approved these changes

2020-08-25 08:06 UTC, YejiAhn approved these changes
수고많았어요 엘리 🥰

2020-08-25 08:10 UTC, chws approved these changes
LGTM!
수고하셨습니다

2020-08-25 10:01 UTC, LTTTTTE approved these changes

2020-08-25 10:11 UTC, merged