feature/113 지도에 시간 필터 기능을 구현한다.
woowacourse-teams/2020-doran-doran pull request #127
Opened 2020-08-24 08:32 UTC by YejiAhn

Resolves #113 
리뷰는 화요일까지 해주세요..

2020-08-24 11:40 UTC, LTTTTTE commented on front/src/api/posts.js
> +      startDate: moment().subtract(1, "days").format("YYYY-MM-DD HH:mm:ss"),
24시간전 글을 봐야하는데
1 day를 빼게되면 최대 47시간전 글까지 조회할수 있을거 같아요

2020-08-25 02:14 UTC, LTTTTTE commented on front/src/components/map/PeriodFilterButton.vue
> +    <template v-if="isSliderOpened">
아 오류가있네요

2020-08-25 05:23 UTC, hwookim commented on front/src/components/map/PeriodFilterButton.vue
> +  padding-bottom: 20px;
지금은 오른쪽으로 잘리네요... 어떻게 해결할 수  있을까요?🤔

2020-08-25 15:15 UTC, YebinK requested changes
간단한 코멘트 몇 개 남겼으니 확인 부탁해요~

2020-08-26 01:45 UTC, YebinK approved these changes

2020-08-26 01:45 UTC, YebinK commented on front/src/components/map/PeriodFilterButton.vue
> +      </v-btn-toggle>
```suggestion
      <v-btn-toggle
          v-model="periodFilterChoice"
          background-color="white"
          mandatory
          rounded
          class="period-choices"
      >
        <v-btn value="24hours" small text @click="loadPostsWithinXhours(24)">
          24시간 이내
        </v-btn>
        <v-btn value="7days" small text @click="loadPostsWithinXdays(7)">
          7일 이내
        </v-btn>
        <v-btn value="30days" small text @click="loadPostsWithinXdays(30)">
          30일 이내
        </v-btn>
        <v-btn value="all" small text @click="loadAllPosts">
          전체
        </v-btn>
        <v-btn value="userInput" small text @click="openCalendarModal">
          직접 입력
        </v-btn>
      </v-btn-toggle>
```

디자인 리팩토링입니다~

2020-08-26 02:15 UTC, YejiAhn commented on front/src/components/map/PeriodFilterButton.vue
> +        </v-btn>
메서드를 재사용 가능하게 리팩토링했습니다 🙂

2020-08-26 02:38 UTC, hwookim approved these changes

2020-08-26 02:48 UTC, LTTTTTE approved these changes
멋져요!

2020-08-26 05:51 UTC, merged