feature/128 지도 화면에서 현재위치로 가는 버튼, 글들 새로고침하는 버튼을 추가한다.
woowacourse-teams/2020-doran-doran pull request #129
Opened 2020-08-24 09:29 UTC by YejiAhn

Resolves #128 
간단한 리뷰니 오늘까지 가능할 듯 해요 👏

2020-08-24 17:34 UTC, hwookim requested changes
서비스에 꼭 필요했던 기능인데 빠르게 적용해줬네요! 👍 👍
역시 멋져요 예지니어스~~~ 🥰

몇 가지 리뷰 달았으니 확인 부탁드려요.
추가로, `MapAssistantButtons`로 분리를 해야하나 싶어요.
두 가지가 묶여서 다시 사용될 수 있을까요?🤔

생각해보니 `PostCreateButton`도 원래는 타임라인 페이지에서 사용되어 분리했던 거라, 이제는 분리할 필요가 없기는 하겠네요.
그래도 분리해놓는 게 나으려나...흠....

2020-08-24 17:34 UTC, hwookim commented on front/src/components/map/MapAssistantButtons.vue
> +      :retain-focus-on-click="false"
기본 값이 false던데 넣은 이유가 있을까요?

2020-08-24 17:34 UTC, hwookim commented on front/src/components/map/MapAssistantButtons.vue
> +}
클릭 후에 포커스가 유지되어 어둡게 나오는 걸 방지하기 위함인가요?
그 이후에 다른 지도같은 곳을 클릭하면 다시 포커스가 유지되는 것 같아요. 🤔
![스크린샷 2020-08-25 오전 2 12 00](https://user-images.githubusercontent.com/45786387/91075021-613be280-e678-11ea-8abf-31f67762a4d3.png)

어떻게 해결해야할지는 저도 잘 모르겠어요....😭
내일 같이 고민해보죠!

2020-08-24 17:34 UTC, hwookim commented on front/src/components/map/MapAssistantButtons.vue
> +      await this.$kakaoMap.setCenterByCurrentLocation();
```suggestion
      await this.$kakaoMap
        .setCenterByCurrentLocation()
        .catch(() =>
          this.$store.commit(
            "snackbar/SHOW",
            ERROR_MESSAGE.UNIDENTIFIABLE_LOCATION,
          ),
        );
```

위치 정보를 받을 수 없을 때 로직도 필요할 것 같네요!

2020-08-26 07:46 UTC, LTTTTTE approved these changes

2020-08-26 07:59 UTC, hwookim approved these changes

2020-08-26 13:55 UTC, merged