feature/130 새로 등록된 30분 내 글들에 n 표시를 해준다.
woowacourse-teams/2020-doran-doran pull request #132
Opened 2020-08-24 11:26 UTC by YejiAhn

Resolves #130 
이것도 간단하니 화요일 오전까지 부탁드려요 👏

2020-08-24 15:15 UTC, hwookim requested changes
멋진 기능 👍 👍 
오늘 고생 많았어요 예지~~

2020-08-24 15:15 UTC, hwookim commented on front/src/components/map/PostOverlay.vue
> +    <div class="new-icon" v-if="isRecentPost">N</div>
class를 확인하기 전까진 content 다음에 N이 올거라고 오해할 수도 있겠네요.
댓글 수 다음으로 옮기는 건 어때요?

사실 크게 중요한 건 아니지만요... 😅

2020-08-25 05:40 UTC, YebinK approved these changes
간단한 리뷰 하나 남겼습니다! 수고했어요~ 👍

2020-08-25 05:40 UTC, YebinK commented on front/src/components/map/PostOverlay.vue
> +.new-icon {
`padding: 1px;`
을 추가하면 어떨까요?


아래 사진들을 참고해주세요!
(전)
![image](https://user-images.githubusercontent.com/19922698/91127059-67fe4000-e6e0-11ea-9f99-239e0977e556.png)


(후)
![image](https://user-images.githubusercontent.com/19922698/91127021-5321ac80-e6e0-11ea-9f36-97f3526109dc.png)

2020-08-25 05:48 UTC, LTTTTTE commented on front/src/components/map/PostOverlay.vue
> +      const postCreatedAt = moment(this.post.createdAt).format(
```suggestion
      const halfAnHourAgo = this.$moment()
        .subtract(30, "minutes")
        .format("YYYY-MM-DD HH:mm:ss");
      const postCreatedAt = this.$moment(this.post.createdAt).format(
```

2020-08-25 08:22 UTC, chws approved these changes
멋진 기능이에요!
다른 팀원들이 남겨준 리뷰 바탕으로 조금만 수정하면 될 것 같아요.
수고하셨습니다 예지니어스~!

2020-08-25 10:00 UTC, LTTTTTE commented on front/src/components/map/PostOverlay.vue
> +      const postCreatedAt = moment(this.post.createdAt).format(
모먼트를 import없이 사용할수 있어요!

2020-08-26 08:24 UTC, LTTTTTE approved these changes

2020-08-26 11:15 UTC, hwookim approved these changes

2020-08-26 14:03 UTC, merged