feature/144 Member 정보수정/로그아웃/회원탈퇴 프론트를 구현한다.
woowacourse-teams/2020-doran-doran pull request #149
Opened 2020-08-25 20:54 UTC by YebinK

Resolves #144

리뷰는 ASAP !

2020-08-25 21:46 UTC, hwookim requested changes
고생 많아요 엘리~~~~~
안주무시나요~~~~~

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberSidebar.vue
> +      <div class="ma-5 mt-10 mb-5" @click="login">
mb-5는 안줘도 되지 않나요?

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberSidebar.vue
> +      await api.deleteMember();
실패한 경우에는 어떻게 되죠?
logout도 함께 확인해주세요.

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberSidebar.vue
> +      this.$router.push("/login");
logout후에는 안가는데 탈퇴 후에는 /login으로 가는 차이가 생긴 이유가 있나요?

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberUpdateModal.vue
> +    }
쓰는 이유가 있나요?

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberUpdateModal.vue
> +            :disabled="this.nicknameNotChanged()"
```suggestion
            :disabled="nicknameNotChanged()"
```

vue template 내에서는 this를 붙일 일이 없어요!

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberUpdateModal.vue
> +          </v-btn>
```suggestion
    <transition name="bounce" @after-leave="close">
      <div v-if="rendered" class="pa-6 pb-1 modal-container">
        <VTextField
          label="새 닉네임을 입력하세요."
          color="grey darken-2"
          v-model="newNickname"
          @keypress.enter="updateMember"
        />
        <div class="button-box">
          <v-btn
            text
            class="mb-2 text-subtitle-1 font-weight-bold grey--text text--darken-1"
            @click="bounceOut"
          >
            취소
          </v-btn>
```

```javascript
    bounceOut() {
      this.rendered = false;
    },
```

이렇게 주면 모달창을 종료할 때도 트랜지션이 가능해요!
그리고 submit 상황이 아니라면 prevent는 필요하지 않아요.

2020-08-25 21:46 UTC, hwookim commented on front/src/components/member/MemberUpdateModal.vue
> +    },
```suggestion
    close() {
      this.$emit("close");
    },
```
~Modal 내의 함수이니 그냥 close로 표현해도 괜찮을 것 같아요.

2020-08-25 21:46 UTC, hwookim commented on front/src/store/modules/member.js
> +    },
로그아웃을 하면 /login으로 이동하고 그 이후에 둘러보기를 눌렀을 때 해당 로직이 실행되야하지 않을까요?

2020-08-26 03:17 UTC, LTTTTTE commented on front/src/components/member/MemberSidebar.vue
> +          <VSpacer/>
```suggestion
          <VSpacer />
```

2020-08-26 04:43 UTC, LTTTTTE commented on front/src/components/member/MemberSidebar.vue
> +          action: this.ooenUpdateMemberModal,
메소드명 오타 예상합니다.

2020-08-26 05:14 UTC, YebinK commented on front/src/components/member/MemberSidebar.vue
> +      await api.deleteMember();
catch로직을 추가 구현했습니다.
현재 이 요청 외에도 다른 요청에 catch가 모두 빠져있는데 예외처리 구현이 시급하네요 😄

2020-08-26 06:17 UTC, LTTTTTE approved these changes

2020-08-26 09:06 UTC, hwookim approved these changes

2020-08-26 09:06 UTC, merged