feature/137 로그인한 사용자의 글/댓글 프론트 기능을 구현한다.
woowacourse-teams/2020-doran-doran pull request #154
Opened 2020-08-26 08:48 UTC by chws

Resolves #137

2020-08-26 18:31 UTC, hwookim requested changes
고생하셨어요!🥰
몇가지 리뷰를 달았으니 확인 부탁드려요.

추가로, 글로만 설명하기는 여러 부분에 걸쳐 있어서 제가 임의대로 수정한 브랜치를 첨부할게요.
[woo/feature/137](https://github.com/woowacourse-teams/2020-doran-doran/tree/woo/feature/137)

2020-08-26 18:31 UTC, hwookim commented on front/src/components/post/CommentItem.vue
> +      :type="'comment'"
타입을 전달하기 보다는 remove 메소드를 전달하는 건 어떨까요?
그렇다면 하위에서 emit을 할 필요도 적어질 거예요.

2020-08-26 18:31 UTC, hwookim commented on front/src/components/post/OptionsModal.vue
> +  transform: translate(-50%, -50%);
만일 트렌지션을 넣고 싶으시다면 translate역시 트랜지션의 일부라는 점을 알아두셔야해요!

2020-08-27 02:48 UTC, chws commented on front/src/components/post/ConfirmModal.vue
> +  name: "ConfirmModal",
신고기능에서 재사용할 것을 생각했어요!
나중에 기능 덧붙이기 쉽게 수정해볼게요

2020-08-27 06:07 UTC, YebinK approved these changes

2020-08-27 06:11 UTC, hwookim approved these changes

2020-08-27 06:12 UTC, chws commented on front/src/components/post/CommentItem.vue
> +      :type="'comment'"
우 브랜치 참고했습니다~~

2020-08-27 06:12 UTC, merged