feature/167 PeriodFilterButton 리펙토링
woowacourse-teams/2020-doran-doran pull request #173
Opened 2020-08-28 03:39 UTC by hwookim

resolve #167 

- 기간 필터 `v-btn-toggle`에 트랜지션 적용
- 변수명, 함수명 간결화
- 캘린더를 꺼도 기존 데이터가 사라지지 않도록 함
  - `DatePickerMenu` 렌더링 방식 변경 (v-if -> show)
- `v-btn-toggle` 내부 각 버튼 v-for로 렌더링
  - `utils/periodFilter` 이용
  - 객체 내부에서 함수를 가지고 있게 함
- buttonType 삭제 -> buttonColor만 가지게 함

리뷰는 언제까지가 적당할지 모르겠네요.

2020-08-29 14:47 UTC, YebinK requested changes
수고했어요 우!
방학이 시작되고 첫 번째 PR이네요!
몇 가지 피드백 남겼으니 확인 부탁해요~

2020-08-29 14:47 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +      this.$emit("select", this.date);
emit의 이벤트명이 점차 `"close-modal"` -> `"close"`, `"select-date"` -> `"select"` 이런 식으로 변경되고 있는 것 같은데 저는 찬성이에요!

2020-08-29 14:47 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      :color="buttonColor"
색깔과 관련해서 현재 `index.css` 안에도 .doran-doran-color가 정의되어 있는데요!
이들을 한곳에서 관리할 수 없을까요? 🤔

2020-08-29 14:47 UTC, YebinK commented on front/src/utils/periodFilter.js
> +export const PERIOD_FILTERS = {
이런 것도 enum이라고 할 수 있을까요?
감탄이 나오네요.. 👍

2020-08-29 14:47 UTC, YebinK commented on front/src/utils/periodFilter.js
> +export const PERIOD_FILTERS = {
+제안) 파일명을 periodFilter보다는 periodOptions는 어떤가요?
4가지 중 하나를 선택할 수 있다는 의미가 좀 더 직관적으로 느껴지네요!

2020-08-29 14:47 UTC, YebinK commented on front/src/utils/periodFilter.js
> +    action: () => store.commit("filter/SET_FILTER_FROM_X_HOURS_AGO_TO_NOW", 24),
해당 메소드는 "24시간 이내"인 경우에만 쓰이고 있는데요. 그래서 인자로 항상 24가 넘어오고 있네요.

이처럼 modules/filter.js에서 관리하고 있는 함수들이 재사용을 위해 저런 네이밍과 인자를 받는 것은 이해했습니다!
다만 우리의 선택지에 `36시간 이내`, `48시간 이내` 이렇게 24 외의 값이 넘어오는 경우가 없는 것을 고려하면
modules/filter.js에서 그냥 `SET_FILTER_DAY`, `SET_FILTER_xxx` 이런 식으로 PERIOD_FILTERS의 상수 하나마다 메소드를 따로 가져가는 방법도 있을 것 같네요! 
마찬가지로 아래 SET_FILTER_FROM_X_DAYS_AGO_TO_NOW 메소드도 한번에 이해하기 힘들기 때문에 `SET_FILTER_WEEK`, `SET_FILTER_MONTH` 이렇게 두 가지 메소드로 만들어도 무방할 것 같습니다!
우는 어떻게 생각하시나요? 🙂

2020-08-29 14:47 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      @after-enter="openCalendar"
after-enter 시에 openCalendar가 필요한가요? 🤔

2020-08-31 15:48 UTC, hwookim commented on front/src/utils/periodFilter.js
> +export const PERIOD_FILTERS = {
좋은 아이디어라고 생각해요 👍 👍

2020-08-31 16:02 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      @after-enter="openCalendar"
직접 입력이 선택된 상태라면 보여야한다고 생각했는데 엘리는 어떻게 생각하시나요?

2020-08-31 16:05 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      :color="buttonColor"
class가 아니라 color로 넣다보니 그 생각을 못했네요. 😅
이젠 이렇게 표시되겠군요!
![스크린샷 2020-09-01 오전 1 04 26](https://user-images.githubusercontent.com/45786387/91741019-175e7980-ebef-11ea-98fa-91aeea8cc2f9.png)

2020-08-31 17:07 UTC, hwookim commented on front/src/utils/periodFilter.js
> +    action: () => store.commit("filter/SET_FILTER_FROM_X_HOURS_AGO_TO_NOW", 24),
기존의 이름이 확실히 가독성이 떨어지긴 하는 것 같네요.🤔

좀 다른 방식으로 접근해봤는데요.
[커밋](https://github.com/woowacourse-teams/2020-doran-doran/pull/173/commits/8e5891c3a16acef641d2ac2c7de25b1f5e762681)에서 다른 방향으로 변경해보았어요.

SET_FILTER_DAY, WEEK 등으로 분리하기 보다는 외부에서 startDate, endDate를 변경하는 게 맞지 않을까? 하는 생각으로 바꿨습니다.
이후에도 몇가지 변경했는데.... 또 PR사이즈가 커져만 가는 느낌도 드네요....😅
전체적으로 한번 보시고 해당 부분 다시 리뷰 부탁드려요~~

2020-09-08 06:07 UTC, chws approved these changes
수고하셨습니다 우
훨씬 깔끔해진것 같아요!

2020-09-08 08:33 UTC, LTTTTTE commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      @before-leave="closeCalender"
calendar로 통일이필요합니다.

2020-09-08 08:55 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      @before-leave="closeCalender"
와우 눈치 못채고 있었네요. 매의눈 👍 👍

2020-09-08 09:42 UTC, LTTTTTE approved these changes
엄청나게 깔끔해졌네요!!!!

2020-09-08 17:27 UTC, YejiAhn requested changes
기간필터링 관련 코드들이 훨씬 깔끔해졌네요 우! 🥰 
간단한 코멘트들 몇 개 남겼으니 확인해주세요~
(+) 시작날짜와 종료날짜를 담는 v-sheet에 두 컴포넌트들이 위로 약간 쏠린 느낌인데 
이 PR에서 같이 손보면 좋을 것 같아요! 👍

2020-09-08 17:27 UTC, YejiAhn commented on front/src/store/modules/filter.js
> +    startDate: period.ago(24, "hours"),
period.js 파일의 Type 도 export 할 수 있을 것 같군요!

2020-09-09 04:32 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      selected: "24hours",
앗 놓쳤었군요. 감사합니다 👍

2020-09-09 09:16 UTC, hwookim commented on front/src/store/modules/filter.js
> +    startDate: period.ago(24, "hours"),
period 객체에서 return하도록 변경했어요!
음.... PERIOD_TYPE로 별도로 export하는 게 나으려나요? 예지 생각은 어때요?

2020-09-09 09:18 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      @after-enter="openCalendar"
예지 말처럼 적용되도록 `v-if`에서 `v-show`로 변경했습니다.
이왕이면 `직접입력`을 클릭했을 때 포커스가 맞춰지면서 스크롤이 이동하는 동작을 하고싶은데.... 그건 못하겠더라고요 😢

겸사겸사 디자인도 변경했으니 확인 부탁드려요~

2020-09-10 05:14 UTC, YejiAhn commented on front/src/store/modules/filter.js
> +    startDate: period.ago(24, "hours"),
저는 별도 export 로 생각했어요! Type이 period에서만 쓰이는 건 아닌데 약간 맞물리는 느낌이네요.

2020-09-10 05:18 UTC, YejiAhn reviewed
리뷰 반영된거 잘봤어요 우!
한 가지 의논해보면 좋을만한 점은 `직접 입력` 눌렀다가 다른 필터링 버튼 눌렀다가 다시 `직접 입력` 누르는 경우인데요.
첫 번째 `직접 입력` 누른 값이 다른 필터링 거쳤다가 다시 눌러도 그대로 들어가 있네요.
이럴 경우에 이미 들어가 있는 해당 값으로 재필터링 되어야 될 것 같은데 재필터링은 이루어지지 않구요.
요는 
- 직접 입력에 값이 없다 => 아무 필터링도 일어나지 않는다.
- 직접 입력에 값이 차 있다 => 재필터링이 이루어져야 할 것 같다.
입니다. 개인적으로는 다른 필터링 거치고 왔을 때도 값이 차 있어야 되나 싶긴 해요.
한번 가볍게 생각해봐주면 좋을 것 같습니다 🥰

2020-09-10 17:52 UTC, YebinK requested changes
정말 수고했어요 우!
기존 코드를 이렇게 대규모 리팩토링하는게 쉽지 않은데
우는 매번 그 어려운 일을 찰떡같이 해내네요! 👏 
몇 가지 리뷰 남겼으니 확인 부탁합니다~

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
요물이네요 👍

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
hide-details="auto" 속성을 사용하면 아래 message 부분을 없앨 수 있어요!
이 속성과 함께 class="ma-1 pa-0"을 적용하면 딱 적당해보이네요. 우는 어떤가요?

**[기존]**
![image](https://user-images.githubusercontent.com/19922698/92772739-f1975880-f3d6-11ea-978c-7e991f7f0b6b.png)

**[hide-details="auto" 적용 후]**
![image](https://user-images.githubusercontent.com/19922698/92772768-f8be6680-f3d6-11ea-899a-16426c0d8bf6.png)


**[hide-details="auto" + class="ma-1 pa-0"적용 후]**
![image](https://user-images.githubusercontent.com/19922698/92773119-4aff8780-f3d7-11ea-9eb3-de3dbe0fb255.png)

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
+개인적으로 "시작 날짜" 와 "종료 날짜" 글자가 조금 더 작으면 좋을 것 같아요!
위의 시간 필터링 글자 사이즈와 비슷하게요! 🙂

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      elevation="2"
elevation보다는 시간 필터링 슬라이드와 통일하는 게 좋을 것 같아요!
기존 .filter-calendar에 `box-shadow: 1px 1px 8px silver;` 요놈을 추가하면 좋겠네요! 🙂

2020-09-10 17:52 UTC, YebinK commented on front/src/store/modules/filter.js
> +      state.endDate = period.now();
훨씬 깔끔해졌네요! 👍

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +    handleUserInputFiltering() {
`handlerUserInputFiltering()`이라는 말을 들었을 때 어떤 역할을 하는 메소드인지 잘 감이 안 오네요.
`validateDateInput()`은 어떤가요?

2020-09-10 17:52 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +.slide-right-enter-active {
transition 👍

2020-09-10 17:52 UTC, YebinK commented on front/src/utils/period.js
> +import moment from "moment";
이 파일...감탄입니다... 👍

2020-09-10 17:52 UTC, YebinK commented on front/src/utils/period.js
> +
공백은 일부러 둔 것인가요? 🤔

2020-09-10 18:02 UTC, hwookim commented on front/src/utils/period.js
> +
format, now, ago가 각각 함수여서 개행을 했는데요.
현재 kakao-plugin 같은 경우에는 개행이 있고, api의 경우에는 개행이 없네요.

어떻게 하는 게 맞을까요?🤔
저는 개인적으로 메소드끼리는 개행을 하는 게 맞다고 봐요.

2020-09-10 18:06 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +    handleUserInputFiltering() {
단순 `validate`라기에는 메소드 마지막에 `filterPosts`를 실행하는 것이 걸리네요.
handle을 쓴 이유도 date값에 따라서 스낵바를 표출할지, 검색을 실행할지 분기가 나뉘는 메소드라서 정한거고요.
더 좋은 네이밍이 있을까요?😥

2020-09-10 18:27 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      elevation="2"
추가했어요~

2020-09-10 19:53 UTC, hwookim commented
@YejiAhn 

> * 직접 입력에 값이 없다 => 아무 필터링도 일어나지 않는다.
> * 직접 입력에 값이 차 있다 => 재필터링이 이루어져야 할 것 같다.

전자의 경우를 구현해보려했는데 실패해서....😢
할려면 할 수 있겠지만 자꾸 어거지코드가 나와서요... 지금도 충분히 어거지 코드지만요...
일단 이번 이슈에서는 후자의 경우로 가고, 논의 후 변경이 필요하다면 별도의 이슈에서 진행해보도록 할게요!

2020-09-10 19:58 UTC, hwookim commented on front/src/store/modules/filter.js
> +    startDate: period.ago(24, "hours"),
`period.TYPE`을 `PERIOD_TYPE`으로 변경해 별도로 export했습니다!

2020-09-10 20:11 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
스낵바로 오류를 모두 표시하니 텍스트 필드 자체의 안내는 필요 없을 것 같아 `hide-details="false"`로 변경했어요.
각 텍스트 필드에 마진을 주기보다는 외부에서 감싸는 v-sheet에서 위치를 조정하는 게 맞는 것 같아 그에 맞게 변경했습니다!
![스크린샷 2020-09-11 오전 5 01 26](https://user-images.githubusercontent.com/45786387/92796091-daaf3100-f3eb-11ea-8d33-a12b92fe5180.png)
일단은 이렇게 변경되었어요.

텍스트필드의 글자 크기를 조정하고 싶은데.... 여간 쉽지 않네요 😥
vuetify 컴포넌트인 v-text-field에서 생성하는 글자인데... 직접 클래스 따와서 적용하려 해도 적용이 잘 안돼요 😭
어떻게 해야할까요...ㅠㅠ

2020-09-11 08:33 UTC, YebinK commented on front/src/components/map/filter/PeriodFilterButton.vue
> +    handleUserInputFiltering() {
흠 그렇다면 이해가 되네요!
저대로 둬도 될 것 같습니다~

2020-09-11 08:34 UTC, YebinK commented on front/src/utils/period.js
> +
저도 동의합니다! 팀원들과 상의해서 팀벤션으로 가져가 봅시다. 🙂

2020-09-11 09:08 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
`:label="label"`을 `:placeholder="label"`로 바꾸고,
`class="font-size-small"`로 주니까 변경이 되네요!
![image](https://user-images.githubusercontent.com/19922698/92899144-86db3100-f459-11ea-857e-d064ad715610.png)

개인적으로는 `font-size-x-small`도 괜찮은 것 같아요!
그럼 textfield 자체의 사이즈도 줄이는게 깔끔해보여요 👍

2020-09-11 14:18 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
textfield의 사이즈를 줄이면 바로 위의 버튼 그룹이랑 어정쩡하게 되는 느낌이네요....

<img width="494" alt="스크린샷 2020-09-11 오후 11 16 30" src="https://user-images.githubusercontent.com/45786387/92936252-67341080-f439-11ea-8dfc-c29d62e5188e.png">

옆 넓이가 좁은 모바일에서는 조금 괜찮아집니다만...
<img width="368" alt="스크린샷 2020-09-11 오후 11 17 05" src="https://user-images.githubusercontent.com/45786387/92936331-7adf7700-f439-11ea-89df-f981e3c10ef8.png">
음... 일단 이렇게 갈까요?🤔

2020-09-11 14:18 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
아 아이콘 크기가 진짜 너무 애매한 거 같아요. 어떻게 해도....small은 너무 작고 그냥은 큰 기분...?

2020-09-11 14:27 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
데스크탑
<img width="493" alt="스크린샷 2020-09-11 오후 11 26 30" src="https://user-images.githubusercontent.com/45786387/92937377-ca727280-f43a-11ea-9786-b875fa0c3953.png">
모바일
<img width="371" alt="스크린샷 2020-09-11 오후 11 26 41" src="https://user-images.githubusercontent.com/45786387/92937400-d100ea00-f43a-11ea-9734-2db0c784671c.png">

차라리 이게 나은 것 같기도...?

2020-09-12 08:11 UTC, YejiAhn approved these changes

2020-09-12 14:03 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        single-line
아래 것이 더 낫네요!
흠...저도 아이콘 계속 건드려보고 있는데 사이즈가 애메하네요 😢
우선 이 PR은 이쯤에서 두고 나중에 방법을 찾으면 수정해봅시다!

2020-09-12 14:04 UTC, YebinK approved these changes
수고했어요!
이만 approve할게요~ 💯

2020-09-13 09:53 UTC, merged