feature/177 엔티티 삭제 시, DB에서 "삭제" 상태가 되도록 변경한다
woowacourse-teams/2020-doran-doran pull request #179
Opened 2020-08-29 21:14 UTC by YebinK

Resolves #177

- Post, PostLike, Comment, CommentLike 엔티티에 EntityStatus 필드를 추가했습니다.
- 관련된 깨지는 테스트들도 모두 수정했습니다.
- 중간중간 보이는 불필요한 메소드, 잘못된 로직도 리팩토링했으니 확인 부탁해요!

이미 배포된 엔티티에 status를 추가하는 문제는 직접 컬럼 추가 쿼리를 치는 것 외에는 떠오르지 않네요 🤔
혹시 방법 있다면 공유 부탁합니다~

방학이니 리뷰는 천천히 해주세요 🙂 즐거운 방학 보내세요!

2020-08-31 17:47 UTC, hwookim requested changes
상태가 DELETE로 변한다면 해당 객체는 클라이언트한테 넘긴 뒤 클라이언트가 필터링 해야 할까요?
아니면 서버가 DELETE 상태의 객체는 필터링한 후 클라이언트에게 살아있는 객체만 넘겨야 할까요?

아직 해당 PR은 이 부분이 해결되지 않아 모든 엔티티의 삭제 로직이 작동하지 않게 되었네요.😭

리뷰로도 남겼듯 좋아요에 대해서는 적용 여부를 고민해봐야 할 것 같아요.
#177 이슈의 목적에 좋아요도 부합할까요? 🤔

2020-08-31 17:47 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/domain/PostLike.java
> +
postLike의 경우에는 지웠다가 다시 누를 수 있을텐데 delete 상태 관리가 효율적일까요?
지금은 DELETE 상태가 되어도 POST에 객체가 남아있고 프론트에서는 그걸 모르니 삭제가 이뤄지질 않네요.

2020-08-31 17:51 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/comment/domain/Comment.java
> +    private EntityStatus status = EntityStatus.ALIVE;
이부분을 놓쳤었네요!
@Builder.Default가 필요하지 않을까요?

---
약간 이번 이슈와는 동떨어졌긴 한데... Builder가 클래스에도 붙어있고 생성자에도 붙어있네요.
한쪽에만 있어도 되지 않나요?

2020-09-08 05:35 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/domain/PostLike.java
> +
동의합니다. 더군다나 postlike, commentlike 생성/삭제 api가  toggle api로 변경된다면요.
반영하겠습니다 🙂

2020-09-08 09:52 UTC, LTTTTTE reviewed
아직 댓글은 "삭제" 상태가 아닌 삭제가 되는거 같군요.
글과 댓글은 초기 status값이 null 입니다.

2020-09-10 04:34 UTC, hwookim requested changes
밤 늦게까지 정말 고생 많으셨어요...!😭
마지막 커밋이 오전 4시 45분이라니..... 쉬고 있는 거 맞죠??

몇가지 리뷰 달았으니 확인 부탁드려요!
진짜진짜 고생 많으셨습니다 ㅠㅠ

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentService.java
> +        System.err.println("====transactinal끝, post delete시작");
디버그용으로 만드셨던 코드는 제거해주세요~😃

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    }
어떤 경우에 `innerJoin`이고 어떤 경우에는 `leftJoin`인 건가요??😢
같은 경우라면 하나로 통일하는 게 맞지 않을까요?

쿼리문도 참 어렵네요....

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/service/PostService.java
>      }
이렇게 보니 `postRepositorySupport`를 사용한 `findById`에서는 예외처리가 안되고 있네요.
만둘어둔 예외를 사용하기 위해서는 `Optional<Post>`를 반환하도록 변경해야하겠어요.

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    public List<Post> findPostWithKeywordAndDate(String keyword, LocalDateTime startDate, LocalDateTime endDate) {
```suggestion
    public List<Post> findPostsWithKeywordAndDate(String keyword, LocalDateTime startDate, LocalDateTime endDate) {
```

List니 Posts로 바꾸는 건 어떨까요?

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    public List<Post> findPostsInBounds(Double leftBound, Double rightBound, Double lowerBound, Double upperBound) {
사용되지 않는 메소드를 미리미리 안지워서 부가적인 테스크가 생겼었네요....😢
죄송합니다ㅠㅠ

2020-09-10 04:34 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    }
`isPost(Comment)Alive` 가 더 맞지 않을까요?

2020-09-10 04:48 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/comment/service/CommentService.java
> +        System.err.println("====transactinal끝, post delete시작");
아이코! 😅

2020-09-10 13:33 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    public List<Post> findPostsInBounds(Double leftBound, Double rightBound, Double lowerBound, Double upperBound) {
ㅋㅋ괜찮습니다.
지우는거 짜릿하네요

2020-09-10 13:36 UTC, chws approved these changes
엘리, 정말 많은 작업을 하셨네요! 특히 querydsl 부분은👍
다른 팀원들이 리뷰를 많이 해줘서 코드가 한결 나아진 것 같아요:)
몇가지만 코멘트 달았어요~ 수고하셨습니다.

2020-09-10 13:36 UTC, chws commented on src/main/java/com/grasshouse/dorandoran/comment/domain/Comment.java
> +    public boolean isAlive() {
이 메소드는 쓰이지 않는 것 같아요!

2020-09-10 13:36 UTC, chws commented on src/test/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupportTest.java
> +        //댓글 2개를 추가한다.
불필요한 주석은 제거해주세요:)

2020-09-10 13:37 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupport.java
> +    }
post와 comment를 `innerJoin`할 경우, 
post.comments가 비어있다면 post는 결과에 포함되지 않습니다.
`leftJoin` (= `leftOuterJoin`)은 post.comments가 비어있어도 post를 가져오는 방식인데요!

현재로서는 통일해도 무방하지만, 메소드 이름만 본다면 지금 상태가 더 적합하겠는데요!
findPostContainingLikes는 말그대로 likes를 포함하고 있는 post를 가져와야 하기 때문입니다. 🙂 
항상 구분해서 써야 하기에 그대로 두면 더욱 공부가 될 수도 있을 것 같은데요!

이 부분은 팀원들과 함께 이야기해봅시다~

2020-09-10 13:43 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/service/PostService.java
>      }
동의합니다.
다만, Optional을 반환하게 하면 이 메소드를 사용하는 모든 곳에서 예외 처리를 해주어야 하는데요,
그리고 그 예외 처리에 분기가 들어갈 것 같지 않네요 🤔  (모두 PostNotFoundException이겠지요?)

그래서 메소드 내에서 예외처리하는 방식으로 변경했습니다!

2020-09-10 15:24 UTC, YebinK commented on src/test/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupportTest.java
> +        //댓글 2개를 추가한다.
테스트 메소드 로직이 길어져서 가독성을 위해 넣어둔 것인데... 🤔 
다함께 이야기해봅시다!

2020-09-10 19:42 UTC, hwookim approved these changes
querydsl은 참 어렵군요..... 왜 fetchjoin에는 on 할 수 없을까....
정말 고생 많으셨어요. 🤣

별달리 리뷰할 부분은 없는 것 같아요.
다만 전체적으로 다시 한번 코드 포맷팅을 돌려봐 주실 수 있을까요?
엘리가 바꾼 부분이 제 포맷터에서는 바뀌기 전으로 돌아오네요....🤔

2020-09-10 19:42 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/controller/PostFilterController.java
> +        List<PostResponse> responses = PostFilterService.showFilteredResults(request);
얘는 왜 바뀐건가욤?

2020-09-10 19:42 UTC, hwookim commented on src/main/java/com/grasshouse/dorandoran/post/service/PostFilterService.java
> +    public List<PostResponse> showFilteredResults(PostFilterRequest request) {
문득 네이밍이 부자연스럽다고 느껴지네요.
`PostService`의 경우엔 `showPosts`와 같이 `Post`를 명시하는데, 필터는 `filteredResults`로 하고 있군요.
`showFilteredPost`는 어떨까요?

2020-09-10 19:51 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/controller/PostFilterController.java
> +        List<PostResponse> responses = PostFilterService.showFilteredResults(request);
바뀐 code convention을 적용했습니다 🙂

2020-09-10 19:53 UTC, YebinK commented on src/test/java/com/grasshouse/dorandoran/post/repository/PostRepositorySupportTest.java
> +        //댓글 2개를 추가한다.
이야기 결과 제거하기로 했습니다 ~

2020-09-10 19:55 UTC, YebinK commented on src/main/java/com/grasshouse/dorandoran/post/service/PostFilterService.java
> +    public List<PostResponse> showFilteredResults(PostFilterRequest request) {
동의합니다!
`PostFilterService.showFilteredResults`,
`PostFilterController.showFilteredResults` 모두 `showFilteredPosts`로 바꿔주었습니다!

기존에 showSearchResult에서 시작된 것이 아닐까 싶네요 ㅎㅎ

2020-09-11 08:52 UTC, LTTTTTE commented on front/src/store/modules/post.js
> +      entityStatus: "",
API요청하면 ALIVE인 친구들만 body에 넣어줄거같은데 response나 front에는 없어도 될거같은 생각이드네요🐰
혹시 필요했다면 어디서 필요했나요?🥕

2020-09-11 09:57 UTC, YejiAhn approved these changes
간단한 코멘트 몇 개 남겼어요!
글과 댓글들을 어드민 입장에서 더 잘 관리할 수 있게 되었군요.
최고에요 엘리 💯

2020-09-11 09:57 UTC, YejiAhn commented on front/src/store/modules/post.js
> +      entityStatus: "",
동의합니다! 프론트에서 어디에 쓰이나 찾아봤는데 쓰이는 곳도 없는 것 같네요 🙂 API 요청을 통해 살아있는/삭제된 인스턴스 전부 다 가져오지 않는 이상 이 필드가 쓰일 경우가 무엇이 있을까요?

2020-09-11 09:57 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/comment/domain/Comment.java
> +        if (Objects.isNull(this.author)) {
👍

2020-09-11 09:57 UTC, YejiAhn commented on src/main/java/com/grasshouse/dorandoran/common/baseentity/EntityStatus.java
> +
불필요한 개행 아닐까요?

2020-09-11 14:30 UTC, hwookim commented on front/src/store/modules/post.js
> +      entityStatus: "",
오 이 문제는 생각을 못했었는데, 예지 리뷰 읽어보니 너무 합당한 거 같아요.
저도 해당 필드는 프론트에서 필요 없다는 생각이 드네요!

2020-09-12 14:36 UTC, LTTTTTE approved these changes

2020-09-12 18:47 UTC, merged