Feature/188 admin 페이지 프론트 스켈레톤 코드를 만든다.
woowacourse-teams/2020-doran-doran pull request #195
Opened 2020-09-09 06:33 UTC by chws

Resolves #188

2020-09-09 07:44 UTC, hwookim requested changes
고생하셨어요~😃
몇가지 리뷰 남겼으니 확인 부탁드려요.

처음에 생기는 불필요한 파일은 제거해주세요.

vuex 의존성이 지금은 사용되지 않는데 후에는 필요할까요?🤔
admin 코드는 최대한 간결하고 가볍게 가야한다고 생각해요.
레베카는 어떻게 생각하시나요?

2020-09-09 07:44 UTC, hwookim commented on front-admin/src/router/index.js
> +    path: "/manage-report",
경로는 `reports`로 가도 괜찮지 않을까요?

2020-09-09 07:44 UTC, hwookim commented on front-admin/src/App.vue
> +        { to: "/manage-report", title: "신고 관리", icon: "mdi-bell" },
prettier 적용된 부분인가요?
다른 곳에서는
```javascript
{
  key: value,
}
```
이런 식으로 했던 것 같아요.😃

2020-09-09 07:44 UTC, hwookim commented on front-admin/src/App.vue
> +      <v-spacer></v-spacer>
```suggestion
      <VAppBarNavIcon @click.stop="drawer = !drawer" />
      <v-toolbar-title> 도란도란 </v-toolbar-title>
      <VSpacer />
```
빈 컴포넌트는 셀프 클로징을 하기로 했었어요.

2020-09-09 07:44 UTC, hwookim commented on front-admin/src/App.vue
> +      drawer: null,
true, false가 와야하지 않나요?
`v-app-bar-nav-icon`에서 `drawer = !drawer`가 되는데 null이어도 괜찮을까요?

물론 javascript에서는 null이 false로 인식될테지만.... 저는 조금 불편하네요🤔

2020-09-09 07:44 UTC, hwookim commented on front-admin/src/assets/index.css
> +}
사용되지 않는 것 같아요~
admin에까지 색상을 정할 필요도 없을 것 같구요~~😄

2020-09-09 09:50 UTC, chws commented on front-admin/src/assets/index.css
> +}
이부분 삭제된 줄 알았는데 아니었군요! 삭제했습니다

2020-09-09 09:51 UTC, chws commented on front-admin/src/router/index.js
> +    path: "/manage-report",
OK!

2020-09-09 09:55 UTC, chws commented on front-admin/src/App.vue
> +        { to: "/manage-report", title: "신고 관리", icon: "mdi-bell" },
prettier 적용될 때 자동으로 안돼서 제가 놓쳤나봐요ㅎㅎ수정했습니다

2020-09-09 11:18 UTC, YebinK requested changes
수고했습니다 👍 
몇 가지 피드백 남겼으니 확인해주세요~

2020-09-09 11:18 UTC, YebinK commented on front-admin/src/components/HelloWorld.vue
> +<template>
불필요한 클래스는 제거해주세요!

2020-09-09 11:18 UTC, YebinK commented on front-admin/src/App.vue
> +          to: "/manage-report",
/reports가 되어야 하지 않을까요?

2020-09-09 11:18 UTC, YebinK commented on front-admin/src/App.vue
> +  <v-app>
Home.vue, Report.vue를 보여주는 router-view가 하나 필요할 것 같네요!

2020-09-10 04:32 UTC, YejiAhn approved these changes
다른 팀원들의 피드백을 이미 많이 반영했군요! 👍 
저도 어드민페이지에서 vuex가 쓰일지에 관해서는 의문이에요.
이만 approve 하겠습니다!

2020-09-10 07:40 UTC, YebinK approved these changes
수고했어요 레베카! 👍 
이만 머지할게요 💯

2020-09-10 07:45 UTC, LTTTTTE approved these changes
이슈 이름과 PR명이 조금 차이가 있다 생각이들어요
프론트 페이지를 만들기 보단, 어드민 view init 느낌이네요

2020-09-10 07:49 UTC, hwookim requested changes
오구의 리뷰를 보고 이슈와 PR을 보니 어색함이 느껴지긴 하네요.
`페이지`에 이미 프론트의 의미가 담겨있으니 굳이 프론트라고 두번 말해주지 않아도 괜찮아 보이네요.
`Admin 페이지의 스켈레톤 코드를 작성한다.`정도여도 괜찮을 것 같아요.

2020-09-10 07:49 UTC, hwookim commented on front-admin/src/views/Report.vue
> +  name: "Report",
컴포넌트명이 Report면 나중에 신고 객체를 생성하고 표시할 때 혼란을 야기할 수 있을 것 같아요.
컴포넌트가 페이지인지, 리스트인지, 모달인지, 아니면 단순 아이템인지 명시해주면 방지할 수 있지 않을까요?

ReportPage는 어때요?

2020-09-10 23:05 UTC, chws commented on front-admin/src/views/Report.vue
> +  name: "Report",
이 코드는 뼈대 코드이니 어떤 역할을 하는지 보여줄 수 있다면 충분하다고 생각해요.
신고 관리를 하는 페이지를 나중에 실제로 만들 때 페이지 이름을 변경하거나 상황에 맞게 바꿀 수 있지 않을까요?

2020-09-14 05:05 UTC, hwookim commented on front-admin/src/views/Report.vue
> +  name: "Report",
router-link로 간다는 거는 이미 충분히 page이지 않을까요?
그렇다면 저는 page라고 명시하는 게 맞는 거 같아요

2020-09-14 12:56 UTC, hwookim approved these changes

2020-09-14 22:58 UTC, merged