feature/201 LogRocket을 적용한다.
woowacourse-teams/2020-doran-doran pull request #203
Opened 2020-09-11 13:57 UTC by chws

Resolves #201 
방식은 #200 와 유사합니다.

2020-09-11 15:04 UTC, hwookim requested changes
점점 프로젝트가 풍성해지는군요 👍 
간단한 생각해볼 점 하나 적었어요. 레베카는 어떻게 생각하는지 알려주세요!

2020-09-11 15:04 UTC, hwookim commented on front/src/main.js
> +} from "@/secure/trackingid";
기존의 `appkey.js`에서 관리해도 괜찮지 않을까요?

2020-09-11 22:41 UTC, chws commented on front/src/main.js
> +} from "@/secure/trackingid";
기존의 appkey와는 성격이 다르다고 생각했습니다. 기존에 있던 것은 비밀 api 키 이고 저희 서비스에서 핵심적인 역할을 하고 있다고 생각했고, 이 코드들은 id와 같은 값이며 사용자 패턴 분석 처럼 사용자 관리에 필요한 값이라고 생각했어요. 그 목적이 다르다고 생각해서 분리했습니다.

2020-09-12 14:18 UTC, YebinK approved these changes

2020-09-12 14:18 UTC, YebinK commented on front/src/main.js
> +} from "@/secure/trackingid";
분리한 이유가 명확해서 좋네요 👍 

전 개인적으로는 아직 파일 갯수가 많지 않으니 분리해도 좋을 것 같네요.
나중에 프론트에서도 모듈 분리같은 작업을 한다면 분리하기도 훨씬 편할 것 같아요.

2020-09-13 14:00 UTC, chws commented
user identify 코드를 추가하면 사용자를 구분할 수 있기 때문에 추가했습니다. 그런데 이 부분은 테스트가 안돼서 코드를 적절한 위치에 넣었는지 확인을 하기가 어렵네요..😢 확인해보시고 의견 주세요~

2020-09-13 15:52 UTC, hwookim approved these changes

2020-09-13 15:52 UTC, hwookim commented on front/src/store/modules/member.js
> +      LogRocket.identify(member.id);
loadMember는 app.vue에서 한번밖에 불리지 않으니 여기서 호출하는 것이 맞는 것 같네요 👍

2020-09-14 05:54 UTC, YejiAhn approved these changes

2020-09-14 06:16 UTC, LTTTTTE approved these changes

2020-09-14 06:33 UTC, merged