feature/224 README.md 업데이트
woowacourse-teams/2020-doran-doran pull request #225
Opened 2020-09-17 06:32 UTC by YebinK

Resolves #224 

확인해주세요!

2020-09-17 06:52 UTC, chws approved these changes
수고하셨습니다 엘리~~

2020-09-17 07:09 UTC, hwookim requested changes
간단한 피드백 몇 개 남겨뒀어요.
이제야 훵했던 저장소 메인페이지가 조금 예뻐지겠네요!

2020-09-17 07:09 UTC, hwookim commented on README.md
> +집 앞에서 고양이를 봤는데 주변 사람들과 공유하고 싶었던 적 있으신가요?
사진 기능이 시급하군요....😅

2020-09-17 07:09 UTC, hwookim commented on README.md
> +- 키워드 검색과 날짜 필터링도 가능합니다.
```suggestion
- 카카오 로그인을 하고,
- 원하는 위치에 글을 남겨보세요.
- 근처에 있는 사람들과 정보를 주고받을 수 있어요.
- 특정 키워드, 기간의 글을 찾아볼 수도 있답니다.
```

이런 느낌은 어떨까요?

2020-09-17 07:09 UTC, hwookim commented on README.md
> +**AWS** `EC2`
Server나 Cloud가 aws ec2 아닐까요?
AWS 자체를 기술 스택으로 볼 수 있는지 좀 헷갈리네요.🤔

2020-09-17 07:30 UTC, YebinK commented on README.md
> +A. 글이 써져있는 위치와 댓글 작성자 간의 거리입니다. 댓글 작성자가 얼마나 가까이서 댓글을 작성했는지 확인할 수 있어요.
저도 그게 가장 좋은 방법이라고 생각해요!
다만 아직 기능 구현이 안 되어있어서 문제네요 🤔 
노션에 모아뒀다가 나중에 추가하면 좋을 것 같아요!

2020-09-17 07:31 UTC, YebinK commented on README.md
> +**AWS** `EC2`
Server: `AWS EC2`가 더 적합하겠네요!

2020-09-17 08:15 UTC, LTTTTTE commented on README.md
> +<img src="https://user-images.githubusercontent.com/19922698/93428397-503e6400-f8fa-11ea-9456-c7f2d5741ed6.gif" width="200">
저도 사이즈가 두배는 컸으면 하네요~

2020-09-17 08:32 UTC, hwookim commented on README.md
> +A. 글이 써져있는 위치와 댓글 작성자 간의 거리입니다. 댓글 작성자가 얼마나 가까이서 댓글을 작성했는지 확인할 수 있어요.
리드미에는 굳이 없어도 괜찮을 것 같아요~~

2020-09-17 12:36 UTC, LTTTTTE approved these changes

2020-09-17 14:34 UTC, YejiAhn reviewed
간단한 코멘트 몇 개 달았어요!
깃헙 레포가 한 층 더 예뻐졌네요 👍

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +집 앞에서 고양이를 봤는데 주변 사람들과 공유하고 싶었던 적 있으신가요?
```suggestion
집 앞에서 고양이를 본 이야기를 주변 사람들과 공유하고 싶었던 적이 있으신가요?
```

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +<img src="https://user-images.githubusercontent.com/19922698/93428397-503e6400-f8fa-11ea-9456-c7f2d5741ed6.gif" width="200">
저도요 🙂🙂

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +- 키워드 검색과 날짜 필터링도 가능합니다.
`키워드 검색과 기간 필터링도 가능합니다`는 어떨까요?

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +🙆 본 서비스는 모바일 사용을 권장합니다.
저도 문구 자체는 사이트 근처에 있으면 좋을 것 같아요!
그리고 관련해서 오늘 피드백 받고 왔는데 내일 회의에서 공유할게요 😎

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +
```suggestion

<br />

```

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +### 📝 Bug Report
이모지 🐛 는 어떨까요? ㅎㅎ
(두어 달 전 레이블에서 징그럽다고 빼자고 했던게 생각나네요)

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/65c05a69-adc4-4ebe-9b1e-c099c4dc4303/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/65c05a69-adc4-4ebe-9b1e-c0
사진 잘 보이나요?

2020-09-17 14:34 UTC, YejiAhn commented on README.md
> +### ❓ QnA
QnA는 노션 프론트 페이지에 추가해도 좋을 것 같군요! 🙂

2020-09-17 17:16 UTC, YebinK commented on README.md
> +- [정주용(오구)](https://github.com/LTTTTTE)
닉네임과 이름을 한 번 언급하는 건 좋은 것 같아요 🙂

2020-09-17 17:21 UTC, YebinK commented on README.md
> +### 📝 Bug Report
ㅋㅋㅋㅋㅋㅋ너무 마음에 듭니다 🐛

2020-09-17 17:21 UTC, YebinK commented on README.md
> +![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/65c05a69-adc4-4ebe-9b1e-c099c4dc4303/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/65c05a69-adc4-4ebe-9b1e-c0
없애버렸습니다!

2020-09-17 17:23 UTC, YebinK commented on README.md
> +- 키워드 검색과 날짜 필터링도 가능합니다.
개인적으로 `필터링` 이라는 단어가 들어가야 와닿는 것 같아요!
`특정 키워드, 특정 기간으로 필터링도 가능합니다.` 는 어떤가요?

2020-09-18 01:14 UTC, hwookim approved these changes

2020-09-18 01:16 UTC, YejiAhn approved these changes

2020-09-18 01:28 UTC, merged