feature/231 검색창의 검색 기능을 키워드가 아닌 위치+상호 검색으로 변경한다.
woowacourse-teams/2020-doran-doran pull request #238
Opened 2020-09-28 07:35 UTC by YebinK

Resolves #231 

사용자 피드백을 반영해 검색창의 검색을 "위치", "상호" 검색으로 변경합니다.

이제 검색창에서 지역 이름이나 상호명을 검색하면 해당 검색 결과가 있는 지역으로 이동합니다.
마커를 클릭하면 상세 상호명을 확인할 수 있습니다.

검색 결과가 없는 경우의 예외 처리도 구현되어 있습니다.

2020-10-03 19:20 UTC, hwookim requested changes
좋은 기능이네요.
앞으로 키워드 필터링을 어떻게 배치하고 사용할지도 고민해야겠군요...

이 이슈를 시작으로 논의해야하 것들이 많아지는 것 같아요.
검색 결과의 필터링은 순전히 카카오 api측의 권한일까요? 잠실역에서 홈플러스를 검색하면 그 근처의 홈플러스가 우선적으로 보이면 좋을텐데 말이죠...🤔

보다보면 컨벤션이 꼬여가는 것도 있는 것 같아요.
한 곳에서만 사용하는 에러 메세지도 모두 constants에서 관리하는 게 맞나요?
처음에는 아니었던 것 같은데 어느 순간 그렇게 되었네요... 전체적으로 수정해야하려나요..😥

몇가지 리뷰 달아뒀는데, 전체적으로 제가 수정해본 코드를 이곳에 올려놓도록 할게요.
추석 연휴인데도 고생 많으십니다!

```javascript

  const _setPlaceOverlay = (name, location) => {
    if (!placeOverlay.getMap()) {
      placeOverlay.setContent(
        `<div class='place-overlay-style font-size-x-small'>${name}</div>`,
      );
      placeOverlay.setPosition(_createKakaoLocation(location));
      placeOverlay.setMap(map);
    } else {
      placeOverlay.setMap(null);
    }
  };

  const _setPlaceMarker = (place, bounds) => {
    const location = {
      longitude: place.x,
      latitude: place.y,
    };
    const marker = setMarker(location);
    placeMarkers.push(marker);

    kakao.maps.event.addListener(marker, EVENT_TYPE.CLICK, () =>
      _setPlaceOverlay(place.place_name, location),
    );

    bounds.extend(_createKakaoLocation(location));
  };

  const _searchPlaceCallBack = (data, status, reject) => {
    if (status === kakao.maps.services.Status.OK) {
      const bounds = new kakao.maps.LatLngBounds();
      data.forEach((place) => _setPlaceMarker(place, bounds));
      map.setBounds(bounds);
    } else {
      reject();
      throw new Error(status);
    }
  };
```

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  };
사용되는 메소드인가요?

2020-10-03 19:20 UTC, hwookim commented on front/src/components/map/KakaoMap.vue
> +    this.$kakaoMap.initPlaceSearch();
`$kakaoMap.drawMap()`에 포함되어도 될 것 같아요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  const _displayMarker = (place) => {
기존의 `$kakao.setMarker`를 이용해도 될 것 같아요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  const clearPlaceMarkers = () => {
글 작성 버튼을 눌렀을 때도 실행되면 좋을 것 같아요.
appbar도 원상태로 돌리면서요.

![스크린샷 2020-10-04 오전 3 34 16](https://user-images.githubusercontent.com/45786387/94999160-0ff00e80-05a7-11eb-97fa-8a7dd93da54c.png)
지금은 요로콤 하네요...😅

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +      }
```javascript
      for (let i = 0; i < data.length; i++) {
        console.log(data[i]);
        const location = {
          longitude: data[i].x,
          latitude: data[i].y,
        };
        const marker = setMarker(location);
        placeMarkers.push(marker);
        kakao.maps.event.addListener(marker, EVENT_TYPE.CLICK, () => {
          placeOverlay.setContent(
            "<div class='place-overlay-style font-size-x-small'>" +
              data[i].place_name +
              "</div>",
          );
          placeOverlay.setPosition(_createKakaoLocation(location));
          placeOverlay.setMap(map);
        });
        bounds.extend(_createKakaoLocation(location));
      }
```

물론 메소드는 분리해야겠지만,
`_displayMarer`를 없애고 기존의 `setMarker`를 쓴다면 이렇게 변경해볼 수 있을 것 같아요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    });
메소드 분리가 이뤄지면 좋겠어요.
템플릿도 따로 분리할 수 있을 것 같아요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    if (status === kakao.maps.services.Status.OK) {
Status 목록을 보니 OK, ZERO_RESULT, ERROR밖에 없더라고요.
OK를 제외한 상황은 모두 오류로 생각하고 관리해도 되지 않을까요?

```javascript
if (status === kakao.maps.services.Status.OK) {
  // ...
} else {
  reject();
  throw new Error(status);
}
```
이런 식으로요.

음... ERROR일 경우의 스낵바도 있어야 하려나요🤔
그렇게 되면 Fail과 NoResult를 분기해야겠네요. 외부의 스낵바도요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  const _searchPlaceCallBack = (data, status, reject) => {
네이밍이....🤔
근데 막상 좋은게 떠오르진 않네요ㅠ

2020-10-03 19:20 UTC, hwookim commented on front/src/components/DoranAppBar.vue
>        await this.$store.dispatch("post/loadPosts");
이젠 불필요한 친구들이네요.

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    if (placeOverlay.getMap !== null) {
```suggestion
    if (placeOverlay.getMap()) {
```
이렇게만 표현해도 작동합니당

2020-10-03 19:20 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +      placeOverlay.setMap(map);
```suggestion
    if (!placeOverlay.getMap()) {
      placeOverlay.setContent(
        `<div class='place-overlay-style font-size-x-small'>${name}</div>`,
      );
      placeOverlay.setPosition(new kakao.maps.LatLng(place.y, place.x));
      placeOverlay.setMap(map);
    } else {
      placeOverlay.setMap(null);
    }
```

다시 눌렀을 때는 꺼지도록 하면 어떨까요?

2020-10-06 04:16 UTC, chws reviewed
엘리! 수고하셨어요👏
검색 결과가 뜰 때 사용자 위치에 가까운 결과가 뜬다면 더 좋을 것 같은데 구현이 어렵네요😢
몇가지 코멘트 남겼으니 확인해주세요~

2020-10-06 04:16 UTC, chws commented on front/src/plugins/kakao-map.js
> +  let infoWindow = null;
이 변수도 사용이 안 되고 있는 것 같아요~

2020-10-06 04:16 UTC, chws commented on front/src/plugins/kakao-map.js
> +      map.setBounds(bounds);
여기에 지도 API의`map.setLevel()`을 사용하면 검색했을 때 
결과가 사용자 위치 주변으로 나올 수 있도록 할 수 있을 것 같아요🤔

2020-10-10 17:32 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  };
InfoWindow -> CustomOverlay로 변경하면서 미처 지우지 못했네요. 반영했습니다!

2020-10-10 18:39 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  const clearPlaceMarkers = () => {
확인해보니 기존에 키워드 검색 시절에도 존재하던 부분이었네요.
해결했습니다!

2020-10-10 20:13 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  const _displayMarker = (place) => {
흠 저도 중복 로직이라는 생각이 들어서 setMarker로 변경하는 것엔 동의합니다.
하지만 setMarker는 custom image를 인자로 받고 있고, 현재는 image가 필요 없는 상태이니까 setMarker 내부에서 분기처리가 필요한데, 흠... 분기처리는 좋은 방법 같지는 않아요!

- placeMarker에 대한 custom image를 추가하거나,
- setMarkerWithImage, setMarker 메소드 분리

두 가지 방법이 있을 것 같아요. 우선 후자로 해둘게요 ㅎㅎ의견 주세요!

2020-10-10 20:15 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +      }
[요놈](https://github.com/woowacourse-teams/2020-doran-doran/pull/238#discussion_r502827935) 참고해주세요!

2020-10-10 20:29 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  };
[달아주신 코멘트](https://github.com/woowacourse-teams/2020-doran-doran/pull/238#pullrequestreview-501563625) 관련해 이야기를 나누자면,
검색결과의 주변 필터링 기능은 [keywordSearch의 option](https://apis.map.kakao.com/web/documentation/#services_Places_keywordSearch)을 통해 특정 location을 중심으로 검색할 수 있어요!

다만 이 기능을 위해서는 몇 가지 추가 논의가 필요해보여요.

- 특정 location을 어디로 잡을건지 (우가 말한대로라면 사용자 현재위치가 될 듯 싶은데)
  - 만약 사용자 현재위치라면, 멀리 떨어진 홈플러스를 검색하고 싶을 경우엔 어떻게 할것인지 (해당 위치에 가서 재검색을 누르기?)
- "주변"의 기준이 어디까지인지
- 결과에 따라 지도레벨을 어느 정도로 축소해야 하는지

그래서 우선 이번 PR이 머지되면, 추가 작업을 진행하는게 좋아보이네요!
이제는 `1PR 1기능` 지키고싶네요! ㅎㅎ

2020-10-10 20:30 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +      map.setBounds(bounds);
setLevel은 단순 지도레벨 설정 로직으로 보이네요 🙂 
[요놈](https://github.com/woowacourse-teams/2020-doran-doran/pull/238#discussion_r502829219)! 함께 논의해봅시다!

2020-10-11 02:27 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  };
별도 이슈로 분리해야 하는 것은 맞죠.

특정 location을 잡는 것에 대해서 네이버 지도나 카카오 지도를 보면 `현재 위치 or 지도의 중심 위치` 중 어떤 것을 기준으로 할지 고를 수 있도록 하더라고요.
앞으로 논의를 통해 개선해 나가도록 합시다.

2020-10-11 03:07 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    setMarker: setMarkerWithImage,
외부에서는 여전히 `setMarker`로 쓰이고 있겠네요.

2020-10-11 03:07 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  const searchPlace = (place, reject) => {
어느 순간부터 메소드의 순서가 뒤죽박죽 되어가고 있네요.
한번 대대적인 정리가 필요할 듯 합니다...🤔

지금은 searchPlace가 callback을 호출하는 데 callback이 더 밑에 있고,
callback이 호출하는 메소드들은 callback보다 앞에 있네요.

메소드 A에서 메소드 B를 호출할 때 B는 A보다 먼저 와야할까요 늦게 와야할까요.
지금은 모든 메소드가 컴파일 된 후에 실행해서 순서는 크게 상관 없다만....
과거 javascript를 처음 배울 때 `인터프리터 언어다`라는 기억이 있어서 저는 되도록 B가 먼저 오도록 작성했는데요.
이건 팀 컨벤션으로 어찌할지 논의 후 정해야겠네요.

2020-10-11 03:07 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    const newMarker = new kakao.maps.Marker({
바로 return하지 않고 나누는 이유가 있나요?

2020-10-11 03:07 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +    return _createMarker(map, kakaoLocation, null);
```suggestion
    return _createMarker(map, kakaoLocation);
```

null을 굳이 안넣어도 되긴 하는데... 흠.... 괜찮은 방법일지는 또 모르겠네요.

2020-10-11 03:07 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +  const _displayMarker = (place) => {
```javascript
  const _createMarkerImage = (src, options) => {
    if (!src) {
      return null;
    }
    const size = new kakao.maps.Size(36, 36);
    return new kakao.maps.MarkerImage(src, size, options);
  };

  const _createMarker = (map, position, image) => {
    return new kakao.maps.Marker({ map, position, image });
  };

  const setMarker = (location, img) => {
    if (!map || !location) {
      return;
    }
    const kakaoLocation = _createKakaoLocation(location);
    const markerImage = _createMarkerImage(img);
    return _createMarker(map, kakaoLocation, markerImage);
  };
```

이런 식으로 변경하면 `setMarker` 내부에서는 분기 없이 하나로 통일해서 사용할 수 있긴 합니다.
물론 분기가 있는 거긴 하지만요....🤔

+) 다른 이슈로 갈 문제지만 size까지 외부에서 설정할 수 있도록 하는 것도 괜찮겠네요.

2020-10-11 03:18 UTC, hwookim requested changes
몇가지 리뷰 달았습니다.
답글로 단 부분도 있으니 확인 부탁드려요.

[앞으로 논의 할 것들에 대해](https://github.com/woowacourse-teams/2020-doran-doran/pull/238#discussion_r502855758)
[setMarker에 대해](https://github.com/woowacourse-teams/2020-doran-doran/pull/238#discussion_r502858436)

2020-10-11 03:18 UTC, hwookim commented on front/src/components/DoranAppBar.vue
> +      this.$kakaoMap.searchPlace(this.keyword, this.searchFail);
현재는 search가 예기치 못한 오류로 실패하더라도 `검색 결과 없음`이라고 알려주겠네요.

2020-10-11 03:18 UTC, hwookim commented on front/src/plugins/kakao-map.js
> +import { PLACE_OVERLAY_TEMPLATE } from "@/utils/templates";
이것도 논의가 필요해 보이네요.
postOverlay같은 경우에는 템플릿을 외부에서 주입해줍니다. 플러그인을 최대한 유연하게 가져가기 위한 전략이었는데요.
지금 생각해보니 애초에 우리 서비스에서만 쓰일 플러그인이고, 주입받는 메소드도 `setPostOverlay`면 이미 유연하기도 그른 것 같네요.

몇가지 외부에서 주입받는 형식을 그냥 내부에서 import받고 처리하거나 (엘리의 방식처럼)
아니면 overlay 객체에 대해 유연하게 할 수 있도록 변경하거나....🤔
엘리의 방식이 우리에겐 더 맞는 것 같네요. 별도의 이슈에서 리팩토링이 필요하겠어요.

2020-10-11 17:06 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  const searchPlace = (place, reject) => {
동의합니다 저도 코드 추가하면서 이 부분이 많이 불편했어요.
연관된 메소드를 모아두고, 주석으로 설명을 약간 달아두는 것도 방법일 것 같아요.

2020-10-11 17:09 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +    return _createMarker(map, kakaoLocation, null);
흠 이문제는 팀벤션으로 가져가도 될 것 같아요.
개인적으로 전 명시적으로 null임을 표시하는 게 좋다고 생각하지만 (중간에 있는 kakaoLocation이 null일 경우도 있으니까), 또 프론트엔드 영역에선 보통 어떻게 처리하는지 궁금하네요.

2020-10-14 03:59 UTC, YejiAhn approved these changes
잘 동작하네요! 
머지 전 리포매팅 한번만 해주세요 🙂 
수고 많았습니다 💯

2020-10-14 09:24 UTC, chws approved these changes

2020-10-18 16:49 UTC, YebinK commented on front/src/plugins/kakao-map.js
> +  const searchPlace = (place, reject) => {
이 부분은 현재 브랜치에서 작업할 내용은 아닌 것 같아요.
별도 이슈로 빼두겠습니다!

2020-10-18 20:15 UTC, hwookim approved these changes
고생 많으셨어요~~~!! 👍🏼  👍🏼 

이번 PR을 시작으로 논의할 점이 많이 생겼네요. 🤔
개인적으로는 아직 해당 기능이 완벽한 게 아니라서 이 상태로는 배포되지 않았으면 하는 마음이 있어요.

데일리 때도 생각나면 말하겠지만, 해당 PR이 머지되기 전에 릴리즈 한 번 하는 건 어떨까요?
그리고 다음 배포는 위치 검색 기능에 대한 정책 등이 좀 더 갖춰지고, 기존의 키워드 검색도 어디선가 부활하고 난 다음이면 어떨까 하는 생각입니다.ㅎㅎ

2020-10-20 08:00 UTC, LTTTTTE approved these changes

2020-10-20 08:11 UTC, merged