feature/259 날짜 필터링 로직 변경
woowacourse-teams/2020-doran-doran pull request #262
Opened 2020-11-02 04:42 UTC by YebinK

Resolves #259

1. `전체` 버튼 없애기
2. `직접 입력` 30일로 제한
3. `직졉 입력` 선택 시 기존 캘린더 2개로 선택하던 방식에서 1개로 시작, 종료 날짜 처리할 수 있도록 변경

2020-11-02 17:07 UTC, hwookim requested changes
고생하셨습니다 👍🏼 

몇가지 리뷰 남겼으니 확인 부탁드려요~~

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
>      <v-sheet v-show="isCalendarOpen" class="px-3 py-0 filter-calendar">
![스크린샷 2020-11-03 오전 12 23 01](https://user-images.githubusercontent.com/45786387/97885462-bd06a400-1d6a-11eb-8dcc-d73b325cc064.png)
지금 보니 paddin-top, padding-left는 의미가 없는 친구였네요. 왜지...

![스크린샷 2020-11-03 오전 12 23 55](https://user-images.githubusercontent.com/45786387/97885551-dd366300-1d6a-11eb-81ae-ec1c799d0d51.png)
간혹가다 글자가 잘리는 경우가 있는데요.
min-width 속성을 통해 최소 크기를 지정해 주는 건 어떨까요?

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +  background-color: white;
![스크린샷 2020-11-03 오전 12 27 39](https://user-images.githubusercontent.com/45786387/97885975-63eb4000-1d6b-11eb-9aee-84dc88f99a8a.png)

뭔가 약간 겹치는군요... 해당 클래스에서 margin-top을 통해 좀 떨어뜨릴 수 있을 것 같아요.
left 속성을 통해 위의 녀석과 정렬을 맞출 수도 있긴 한데... 이건 잘 모르겠내요. 약간 depth가 있는 느낌으로 들어간 것도 나쁘진 않으려나요? 🤔

---
<img width="219" alt="스크린샷 2020-11-03 오전 12 31 34" src="https://user-images.githubusercontent.com/45786387/97886423-eecc3a80-1d6b-11eb-86b9-078369e0afd7.png">

min-height에 대한 이슈는 App.vue 파일에서 해당 스타일을 적용했기 때문인데요.
이전에 모바일 화면에서 주소창에 따라 움직이는 이슈 때문에 적용했던 스타일이네요.
확인해보니 app-container 하위에 v-application--wrap 클래스를 가진 div에만 해당 스타일을 적용하면 min-height를 적용하지 않고 height만으로도 높이를 설정할 수 있을 것 같아요.

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +  background-color: white;
버튼의 위치가 너무 아래여서 수정하려 해봤지만 단순 css로는 수정이 불가능하네요.
scss variable을 통해 수정이 가능한데, 몇가지 설정 추가도 필요한 것 같아서 나중에 시간이 될 때 알아보도록 할게요 🤔

~~나중이 있을까...~~

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        this.$store.commit("snackbar/SHOW", ERROR_MESSAGE.INVALID_DATE_COUNT);
하루만 선택했을 때는 자동적으로 그 날 하루의 글을 보여줄 순 없을까요?

개인적으로는 `2020-11-03 ~ 2020-11-03` 보다는 `2020-11-03` 하나만 있는 게 더 깔끔해 보이네요.

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +      }
사용자 입장에서는 시작 날짜를 누르는 것과 종료 날짜를 누르는 순서가 바뀌어도 시각적으로 다르지 않으니 당황스러울 수 있을 것 같아요.
비교를 통해서 자동으로 시작, 종료 날짜를 세팅해줄 수는 없을까요?

moment를 사용하지 않고 단순 `<, >`를 통한 비교로도 `this.dates` 값의 순서는 구분이 가능합니다. 😄

2020-11-02 17:07 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +        return false;
false를 반환하는 이유가 있나요?

2020-11-03 05:30 UTC, LTTTTTE approved these changes
기존 날짜 방식보다 더 좋아진거 같군요!
고생하셨습니다.

2020-11-03 05:30 UTC, LTTTTTE commented on front/src/components/map/filter/DatePickerMenu.vue
> +    <div class="flex-column">
![image](https://user-images.githubusercontent.com/7259103/97952326-502df100-1de0-11eb-8d2a-e4d4407dd3f7.png)

overflow: hidden;을 주니까 옆에 스크롤바가 사라지긴하는데 vue엔 어디적용할지 모르겠네요 ㅎㅎ

2020-11-04 02:17 UTC, chws reviewed
수고하셨어요 엘리! 정말 필요한 기능이네요👍
코멘트 하나 남겼어요~

2020-11-04 02:17 UTC, chws commented on front/src/utils/constants.js
> +  INVALID_OVER_30_DAYS: "😨 최대 30일간 조회가 가능합니다.",
```suggestion
  INVALID_OVER_1_MONTH: "😨 최대 한 달간 조회가 가능합니다.",
```

2020-11-04 02:20 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +  background-color: white;
달력 위치는 수정했습니다!
놓친 부분이었는데 굿 🙂 

버튼 위치는 저게 최선인 것 같아요!

<img src="https://user-images.githubusercontent.com/19922698/98061590-8a0a0080-1e8f-11eb-802c-0c285e2a8bad.png" height="300"/>

이 경우에는 저 위치가 딱 적절해보이네요 ㅎㅎ

2020-11-04 03:41 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +    <div class="flex-column">
css로 적용했습니다!

2020-11-04 03:54 UTC, YejiAhn requested changes
엘리 vue 만지느라 수고했어요! 💯 
간단한 리뷰 몇 개 달았어요~

2020-11-04 03:54 UTC, YejiAhn commented on front/src/utils/period.js
>      title: "직접입력",
밑에 CUSTOM 친구의 order를 4로 바꿔주는 것 어떨까요?
나중에 헷갈릴 수 있을 것 같아요 🙂

2020-11-04 03:54 UTC, YejiAhn commented on front/src/components/map/filter/PeriodFilterButton.vue
> +      this.endDate = period.format(dates[1] + " 00:00:00");
이렇게 되면 10/1부터 10/3까지 설정을 했을 때 10월 3일 글은 포함되지 않게 되겠네요.
반폐구간 말고 폐구간으로 설정하는게 사용자 입장에서 직관적일 것 같아요!

2020-11-04 06:59 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +        return false;
메소드 분리하려고 시도했다다 취소하고 남은 잔여물이네요.. 앞으로 신경쓰도록 하겠습니다!

2020-11-04 06:59 UTC, YebinK commented on front/src/utils/constants.js
> +  INVALID_OVER_30_DAYS: "😨 최대 30일간 조회가 가능합니다.",
좋은 의견이네요 👍

2020-11-05 05:23 UTC, hwookim commented on front/src/components/map/filter/DatePickerMenu.vue
> +      }
startDate, endDate의 순서를 먼저 검증하고 30일 이상 차이나는지 검사해야하지 않을까요?

2020-11-05 05:28 UTC, hwookim requested changes
간단한 리뷰 하나 더 달았습니다!

2020-11-05 05:28 UTC, hwookim commented on front/src/components/map/filter/PeriodFilterButton.vue
> +    inputDates(dates) {
```suggestion
    inputDates({startDate, endDate}) {
```

객체로 반환하면 조금 더 편하지 않을까요? dates[-]을 쓰는 것 보단 나을 것 같아요.😄

2020-11-05 07:36 UTC, chws commented on front/src/components/map/filter/DatePickerMenu.vue
> +      if (startDate < endDate.getMonth() - 1) {
```suggestion
      if (startDate.getMonth() < endDate.getMonth()  && startDate.getDate() <= endDate.getDate()) {
```

2020-11-05 07:36 UTC, chws commented on front/src/components/map/filter/DatePickerMenu.vue
> +      if (startDate < endDate.getMonth() - 1) {
`1102-1201` 가능
`1102-1202` 혹은 그 이상 조회는 불가능

2020-11-05 08:22 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +      if (startDate < endDate.getMonth() - 1) {
moment를 사용하도록 변경했습니다~

2020-11-05 09:49 UTC, chws approved these changes

2020-11-05 09:55 UTC, YebinK commented on front/src/components/map/filter/DatePickerMenu.vue
> +      if (startDate < endDate.getMonth() - 1) {
moment 플러그인을 사용해서 하도록 변경했습니다!

2020-11-05 10:26 UTC, hwookim approved these changes
고생 많으셨어요 엘리! 👍🏼 👍🏼

2020-11-06 07:04 UTC, YejiAhn approved these changes

2020-11-07 13:07 UTC, merged